name: Deploy MCP Server

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "production"
        type: choice
        options:
          - production

jobs:
  # Auto-deploy to staging on release
  deploy-staging:
    if: github.event_name == 'release' && !github.event.release.prerelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Submit to Cloud Build - Staging
        run: |
          gcloud builds submit \
            --config=./.gcloud/cloudbuild-staging.yaml \
            --substitutions=_ENVIRONMENT=staging,_REPO_NAME=${{ github.event.repository.name }},_TAG=${{ github.ref_name }},_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

  # Manual deploy to production
  deploy-production:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Submit to Cloud Build - Production
        run: |
          gcloud builds submit \
            --config=./.gcloud/cloudbuild-staging.yaml \
            --substitutions=_ENVIRONMENT=production,_REPO_NAME=${{ github.event.repository.name }},_TAG=${{ github.ref_name }},_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
